linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - revive
  disable:
    - typecheck  # Disable typecheck to avoid dependency errors

linters-settings:
  govet:
    enable:
      - shadow
  gofmt:
    simplify: true
  revive:
    confidence: 0.8

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
    - ui
    - deployments
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - revive

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - ui
    - deployments
  modules-download-mode: readonly

