# golangci-lint configuration
# Version: v2 format (golangci-lint 2.x)
version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive

  settings:
    govet:
      enable:
        - shadow
    revive:
      confidence: 0.8

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: cmd/
        linters:
          - revive
    paths:
      - vendor
      - ui
      - deployments
      - third_party

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true
