// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type DiffSummary struct {
	Added   int `json:"added"`
	Removed int `json:"removed"`
	Changed int `json:"changed"`
}

type Edge struct {
	From string `json:"from"`
	To   string `json:"to"`
	Kind string `json:"kind"`
}

type Export struct {
	Filename string `json:"filename"`
	Content  string `json:"content"`
}

type Finding struct {
	ID          string `json:"id"`
	RuleID      string `json:"ruleId"`
	Severity    string `json:"severity"`
	EntityRef   string `json:"entityRef"`
	Reason      string `json:"reason"`
	Remediation string `json:"remediation"`
}

type Kv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Neighbor struct {
	ID       string   `json:"id"`
	Kind     string   `json:"kind"`
	Labels   []string `json:"labels"`
	EdgeKind string   `json:"edgeKind"`
}

type Node struct {
	ID        string      `json:"id"`
	Kind      string      `json:"kind"`
	Labels    []string    `json:"labels"`
	Props     []*Kv       `json:"props"`
	Neighbors []*Neighbor `json:"neighbors"`
}

type Path struct {
	Nodes []*Node `json:"nodes"`
	Edges []*Edge `json:"edges"`
}

type Query struct {
}

type Recommendation struct {
	PolicyID           string   `json:"policyId"`
	SuggestedActions   []string `json:"suggestedActions"`
	SuggestedResources []string `json:"suggestedResources"`
	PatchJSON          string   `json:"patchJson"`
	Rationale          string   `json:"rationale"`
}

type Snapshot struct {
	ID        string  `json:"id"`
	CreatedAt string  `json:"createdAt"`
	Label     *string `json:"label,omitempty"`
	NodeCount int     `json:"nodeCount"`
	EdgeCount int     `json:"edgeCount"`
}

type SnapshotDiff struct {
	AddedEdges   []*Edge      `json:"addedEdges"`
	RemovedEdges []*Edge      `json:"removedEdges"`
	Summary      *DiffSummary `json:"summary"`
}
